### ISSUE TITLE
OOM while building VGG-like net

### ISSUE THREAD

**Issue by charlesg3** [thinktopic/cortex#19]
I am trying to load the pre-trained VGG16 net from keras, add two linear->relu 4096 layers and replace the input layer. When trying to build the description with a batch size of 4, I get the following error:

`Exception CUDA Error: out of memory  think.compute.cuda-driver/eval26130/fn--26139 (cuda_driver.clj:349)`

Example code that reproduces this error for me:
```
(defn test-vgg
  []
  (-> (concat (->> "resources/vgg16_combined.h5"
                   (keras/load-combined-hdf5-file)
                   (:model)
                   (drop 1)
                   (concat (desc/input 192 192 3)))
              [(desc/linear->relu 4096)
               (desc/dropout 0.7)
               (desc/linear->relu 4096)
               (desc/dropout 0.7)
               (desc/linear->softmax 40)])
      (compute-desc/build-and-create-network (cuda-backend/create-backend :float) 4)))
``` 

Full Output:
```
loading weights/bias for :conv1_1
Reshaping weights for :conv1_1
loading weights/bias for :conv1_2
Reshaping weights for :conv1_2
loading weights/bias for :conv2_1
Reshaping weights for :conv2_1
loading weights/bias for :conv2_2
Reshaping weights for :conv2_2
loading weights/bias for :conv3_1
Reshaping weights for :conv3_1
loading weights/bias for :conv3_2
Reshaping weights for :conv3_2
loading weights/bias for :conv3_3
Reshaping weights for :conv3_3
loading weights/bias for :conv4_1
Reshaping weights for :conv4_1
loading weights/bias for :conv4_2
Reshaping weights for :conv4_2
loading weights/bias for :conv4_3
Reshaping weights for :conv4_3
loading weights/bias for :conv5_1
Reshaping weights for :conv5_1
loading weights/bias for :conv5_2
Reshaping weights for :conv5_2
loading weights/bias for :conv5_3
Reshaping weights for :conv5_3
Using file input data
Reshaping output for: :conv1_1-activation [224 224 64] 3211264 :Activation
Reshaping output for: :conv1_2-activation [224 224 64] 3211264 :Activation
Reshaping output for: :maxpooling2d_6 [112 112 64] 802816 :MaxPooling2D
Reshaping output for: :conv2_1-activation [112 112 128] 1605632 :Activation
Reshaping output for: :conv2_2-activation [112 112 128] 1605632 :Activation
Reshaping output for: :maxpooling2d_7 [56 56 128] 401408 :MaxPooling2D
Reshaping output for: :conv3_1-activation [56 56 256] 802816 :Activation
Reshaping output for: :conv3_2-activation [56 56 256] 802816 :Activation
Reshaping output for: :conv3_3-activation [56 56 256] 802816 :Activation
Reshaping output for: :maxpooling2d_8 [28 28 256] 200704 :MaxPooling2D
Reshaping output for: :conv4_1-activation [28 28 512] 401408 :Activation
Reshaping output for: :conv4_2-activation [28 28 512] 401408 :Activation
Reshaping output for: :conv4_3-activation [28 28 512] 401408 :Activation
Reshaping output for: :maxpooling2d_9 [14 14 512] 100352 :MaxPooling2D
Reshaping output for: :conv5_1-activation [14 14 512] 100352 :Activation
Reshaping output for: :conv5_2-activation [14 14 512] 100352 :Activation
Reshaping output for: :conv5_3-activation [14 14 512] 100352 :Activation
Reshaping output for: :maxpooling2d_10 [7 7 512] 25088 :MaxPooling2D

Exception CUDA Error: out of memory  think.compute.cuda-driver/eval26130/fn--26139 (cuda_driver.clj:349)
```

**Comment by cnuernber** [comment]
```
(defn test-vgg
  []
  (-> (concat (->> "../keras/models/vgg16_combined.h5"
                   (keras/load-combined-hdf5-file)
                   (:model)
                   (drop 1)
                   (concat (desc/input 192 192 3)))
              [(desc/linear->relu 4096)
               (desc/dropout 0.7)
               (desc/linear->relu 4096)
               (desc/dropout 0.7)
               (desc/linear->softmax 40)])
      (desc/build-full-network-description)
      (desc/get-network-sizes 4 Float/BYTES)))

[{:batched-output-size 1769472, :output-size-in-bytes 442368, :type :input}
 {:batched-output-size 37748736,
  :output-size-in-bytes 9437184,
  :parameters-size 7168,
  :type :convolutional}
 {:batched-output-size 37748736, :output-size-in-bytes 9437184, :type :relu}
 {:batched-output-size 37748736,
  :output-size-in-bytes 9437184,
  :parameters-size 147712,
  :type :convolutional}
 {:batched-output-size 37748736, :output-size-in-bytes 9437184, :type :relu}
 {:batched-output-size 9437184, :output-size-in-bytes 2359296, :type :max-pooling}
 {:batched-output-size 18874368,
  :output-size-in-bytes 4718592,
  :parameters-size 295424,
  :type :convolutional}
 {:batched-output-size 18874368, :output-size-in-bytes 4718592, :type :relu}
 {:batched-output-size 18874368,
  :output-size-in-bytes 4718592,
  :parameters-size 590336,
  :type :convolutional}
 {:batched-output-size 18874368, :output-size-in-bytes 4718592, :type :relu}
 {:batched-output-size 4718592, :output-size-in-bytes 1179648, :type :max-pooling}
 {:batched-output-size 9437184,
  :output-size-in-bytes 2359296,
  :parameters-size 1180672,
  :type :convolutional}
 {:batched-output-size 9437184, :output-size-in-bytes 2359296, :type :relu}
 {:batched-output-size 9437184,
  :output-size-in-bytes 2359296,
  :parameters-size 2360320,
  :type :convolutional}
 {:batched-output-size 9437184, :output-size-in-bytes 2359296, :type :relu}
 {:batched-output-size 9437184,
  :output-size-in-bytes 2359296,
  :parameters-size 2360320,
  :type :convolutional}
 {:batched-output-size 9437184, :output-size-in-bytes 2359296, :type :relu}
 {:batched-output-size 2359296, :output-size-in-bytes 589824, :type :max-pooling}
 {:batched-output-size 4718592,
  :output-size-in-bytes 1179648,
  :parameters-size 4720640,
  :type :convolutional}
 {:batched-output-size 4718592, :output-size-in-bytes 1179648, :type :relu}
 {:batched-output-size 4718592,
  :output-size-in-bytes 1179648,
  :parameters-size 9439232,
  :type :convolutional}
 {:batched-output-size 4718592, :output-size-in-bytes 1179648, :type :relu}
 {:batched-output-size 4718592,
  :output-size-in-bytes 1179648,
  :parameters-size 9439232,
  :type :convolutional}
 {:batched-output-size 4718592, :output-size-in-bytes 1179648, :type :relu}
 {:batched-output-size 1179648, :output-size-in-bytes 294912, :type :max-pooling}
 {:batched-output-size 1179648,
  :output-size-in-bytes 294912,
  :parameters-size 9439232,
  :type :convolutional}
 {:batched-output-size 1179648, :output-size-in-bytes 294912, :type :relu}
 {:batched-output-size 1179648,
  :output-size-in-bytes 294912,
  :parameters-size 9439232,
  :type :convolutional}
 {:batched-output-size 1179648, :output-size-in-bytes 294912, :type :relu}
 {:batched-output-size 1179648,
  :output-size-in-bytes 294912,
  :parameters-size 9439232,
  :type :convolutional}
 {:batched-output-size 1179648, :output-size-in-bytes 294912, :type :relu}
 {:batched-output-size 294912, :output-size-in-bytes 73728, :type :max-pooling}
 {:batched-output-size 65536,
  :output-size-in-bytes 16384,
  :parameters-size 302006272,
  :type :linear}
 {:batched-output-size 65536, :output-size-in-bytes 16384, :type :relu}
 {:batched-output-size 65536, :output-size-in-bytes 16384, :type :dropout}
 {:batched-output-size 65536,
  :output-size-in-bytes 16384,
  :parameters-size 67125248,
  :type :linear}
 {:batched-output-size 65536, :output-size-in-bytes 16384, :type :relu}
 {:batched-output-size 65536, :output-size-in-bytes 16384, :type :dropout}
 {:batched-output-size 640, :output-size-in-bytes 160, :parameters-size 655520, :type :linear}
 {:batched-output-size 640, :output-size-in-bytes 160, :type :softmax}]
cortex-regression.core> (desc/summarize-network-sizes network-sizes)
{:buffer-size-in-bytes 338658560, :parameter-size-in-bytes 428645792}
cortex-regression.core> 
```

**Comment by cnuernber** [comment]
This should have loaded fine on a big card so it is still a bug until I figure out why that didn't happen but I don't think you want this number of trainable parameters in your linear layer.  I would perhaps add a couple more convolutional layers.

**Comment by cnuernber** [comment]
I get a java OOM error trying to load the model directly.

**Comment by charlesg3** [comment]
It turns out that the error occurs when the input size is changed to 192x192 (however using the exact same code with 224 x 224 doesn't yield the OOM). The OOM error occurs when building some of the conv layers.

When looking at the workspaces that are being allocated, we can see below that some of the conv layers are requiring 2GB when the input size is 196x196 and a mere 9K when the input size is 224 x 224.

For each of the two configurations, when building conv layers with channels > 256 (this is where the large allocations occur for the OOM case) I printed out the workspace size, convolution size and a debug print that already existed. See below where the allocation is much higher for the smaller input size.

Good (224x224):
```
ubuntu@ip-172-31-43-50:~/src/think.vgg/src/think$ cat convs.good  | head -n 20
Large conv workspace:  9216
channels: 256 height: 56 width: 56
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 9216
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_0 0
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 0
Large conv workspace:  9216
channels: 256 height: 56 width: 56
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 9216
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_0 0
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 0
Large conv workspace:  9216
channels: 256 height: 28 width: 28
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 9216
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3 0
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 0
Large conv workspace:  18432
channels: 512 height: 28 width: 28
```

OOM (192x192):
```
ubuntu@ip-172-31-43-50:~/src/think.vgg/src/think$ cat convs.oom | head -n 20
Large conv workspace:  2251554816
channels: 256 height: 48 width: 48
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 9216
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT 2224029696
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT 2251554816
Large conv workspace:  2251554816
channels: 256 height: 48 width: 48
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 9216
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT 2224029696
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT 2251554816
Large conv workspace:  1163395072
channels: 256 height: 24 width: 24
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 9216
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT 1145569280
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT 1163395072
Large conv workspace:  2286419968
channels: 512 height: 24 width: 24
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 18432
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT 2286419968
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 0
Large conv workspace:  2286419968
channels: 512 height: 24 width: 24
Convolution algorithm and workspace sizes:
                               Forward: CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM 18432
                               Backward Filter: CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT 2286419968
                               Backward Data: CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 0
Exception in thread "main" java.lang.Exception: CUDA Error: out of memory [...]
```

**Comment by charlesg3** [comment]
Relevant: https://github.com/thinktopic/cortex/pull/22

**Comment by charlesg3** [comment]
`nvidia-smi` running with a vgg-style net and batch-size 32 and the above PR:

```
Fri Nov  4 04:44:23 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:00:1E.0     Off |                    0 |
| N/A   78C    P0    64W / 149W |   6915MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      3304    C   java                                          6913MiB |
+-----------------------------------------------------------------------------+
```

**Comment by cnuernber** [comment]
I believe this issue (and #22) are fixed by this pull request:
https://github.com/thinktopic/cortex/pull/22.

Feel free to reopen if this isn't the case.
